import type { Metadata } from "next";
import {syne, urbanist} from '@/app/fonts'
import "./globals.css";
import Navbar from "@/components/shared/Navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${syne.variable} ${urbanist.variable} h-full antialiased`}
    >  
      <body className="min-h-full flex flex-col font-sans">
        <Navbar/>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
